# Generated by Django 4.1.7 on 2023-02-28 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0002_alter_advertisement_id_favouriteadv'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='add_to_favourite',
            field=models.ManyToManyField(related_name='favourite_advs', through='advertisements.FavouriteAdv', to=settings.AUTH_USER_MODEL),
        ),
    ]
